version: '3.8'
services:
  db:
    image: mariadb:latest
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: SmartHomeManagementSystem
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mariadb-admin", "ping", "--silent" ]
      interval: 30s
      timeout: 10s
      retries: 5

  app:
    build: .
    ports:
      - "8191:8191"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://192.168.189.144:3306/SmartHomeManagementSystem
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8080:80"
    depends_on:
      db:
        condition: service_healthy
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: ""

  frontend:
    build:
      context: ./smart-home-frontend
    ports:
      - "4200:80"
