version: '3.8'

services:
  db:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: SmartHomeManagementSystem
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - mynetwork

  app:
    build:
      context: ./smart-home-backend
    container_name: springboot-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/SmartHomeManagementSystem
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      db:
        condition: service_healthy
    networks:
      - mynetwork

  frontend:
    build:
      context: ./smart-home-frontend
    container_name: frontend-app
    networks:
      - mynetwork

networks:
  mynetwork:
